=head1 NAME

Carton::Doc::Check - Check if your cpanfile and local environment are in sync

=head1 SYNOPSIS

  carton check

=head1 DESCRIPTION

This command checks the consisntency between yoru cpanfile and the
local environment.

=head2 MISSING MODULES

If one of the modules specified in your I<cpanfile> are not found in
your local environment, C<carton check> will warn you about this:

  $ carton check
  Following dependencies are not satisfied. Run `carton install` to install them.
  JSON (2.00)

You can run C<carton install> again to reinstall these missing dependencies.
