=head1 NAME

Carton::Doc::Exec - execute your script in a carton local environment

=head1 SYNOPSIS

  carton exec perl myscript.pl

=head1 DESCRIPTION

This command allows you to run your script in an isolated carton local
environment, which means the perl 5 library path C<@INC> are the only
ones from perl's core library path, carton's library path
(i.e. C<local/lib/perl5>) and the current directory.

This is useful to make sure your scripts and application use the exact
same versions of the modules in your library path, and are not using
any of the modules you accidentally installed into your system perl or
perlbrew's site library path.
