=head1 NAME

Carton::Doc::Uninstall - uninstall modules from your local environment

=head1 SYNOPSIS

  carton uninstall Module

=head1 DESCRIPTION

This command allows you to uninstall modules and its dependencies from
your local environment.

You're only allowed to uninstall modules that are not dependent by
other modules. So if you have a dependency tree like:

  Dancer-2.1
    URI-1.5
  HTTP-Body-1.3
    LWP-1.2
      URI-1.4

you can uninstall either I<HTTP::Body> or I<Dancer>, but when you
uninstall I<Dancer>, because I<URI> is referenced by I<LWP>, it will
uninstall only I<Dancer>.
